### PR TITLE
feat:  Tearsheet ai

### PR DESCRIPTION
**Pull request by lee-chase**
Contributes to https://github.com/carbon-design-system/carbon-for-ai/issues/17

Contributes to #3754 

First draft of AI enhancements for Tearsheet, it is missing the border updates pending updates to the @carbon/react modal dialog.

NOTE: Further changes will be needed when this issues is completed, no reason not to merge this experimental implementation.
https://github.com/carbon-design-system/carbon/issues/15661

#### What did you change?

Added slug property to the Tearsheet, adjusted spacing of actions top right with slug and/or close, added gradient background to content area.

#### How did you test and verify your work?

Storybook

### CODE REVIEW

**Comment by mattrosno** [comment]
@lee-chase this PR is to enhance the React Tearsheet, right? Not build a web component version?

I believe this issue should be linked: https://github.com/carbon-design-system/ibm-products/issues/3754

**Review by davidmenendez — COMMENTED** [review]
LGTM. just need to fix merge conflicts

**Comment by lee-chase** [comment]
Changing to draft pending inclusion of https://github.com/carbon-design-system/carbon/pull/15727 in a Carbon release

**Comment by lee-chase** [comment]
Decided to deal with 15727 updates in additional PR.

**Review by davidmenendez — APPROVED** [review]

**Pull request merged**
