### PR TITLE
feat(NotificationsPanel): include target attribute inside the link - v1

### PR DESCRIPTION
**Pull request by punnoosewilson**
Contributes to #3202 

Enhancement Request for NotificationsPanel Component ‘link’ object to have the ability to ‘open in new window’ when clicked by user. 

#### What did you change?
- Included an extra optional object inside the link. So the consumers can include any of the Link props with in that optional object.

#### How did you test and verify your work?
Storybook

PS: PR for v1

### CODE REVIEW

**Review by davidmenendez — DISMISSED** [review]
i like this idea, but i think this can be simplified. i don't think a new `optional` prop is required. i think simply doing `{...notification.link}` should be sufficient for passing on any extra props.

**Comment by punnoosewilson** [comment]
> i like this idea, but i think this can be simplified. i don't think a new `optional` prop is required. i think simply doing `{...notification.link}` should be sufficient for passing on any extra props.

Hi @davidmenendez ,
We also thought about the same idea. but it had some problem. 
I've mentioned this inside the PR created for v2.
https://github.com/carbon-design-system/ibm-products/pull/3326#issuecomment-1653077177

That's why we introduced an `optional` prop.

**Comment by lee-chase** [comment]
> > i like this idea, but i think this can be simplified. i don't think a new `optional` prop is required. i think simply doing `{...notification.link}` should be sufficient for passing on any extra props.
> 
> Hi @davidmenendez , We also thought about the same idea. but it had some problem. I've mentioned this inside the PR created for v2. [#3326 (comment)](https://github.com/carbon-design-system/ibm-products/pull/3326#issuecomment-1653077177)
> 
> That's why we introduced an `optional` prop.

I can see how {...notification.link} in would be problematic due to the 'text' property.

You can probably get away with 
`{...{...notification.link, text: null}}`

alternatively use the prepareProps utility function.

`{...prepareProps({}, notification.link, ['text'])}`

**Comment by punnoosewilson** [comment]
Thank you for the suggestion @lee-chase. 
I've incorporated prepareProps utility function.
`{...prepareProps({}, notification.link, ['text', 'url'])}`

@davidmenendez @matthewgallo could you review it?

PS: For the consistency I'm planning to do the same update inside v11.

**Review by elycheea — APPROVED** [review]
🎉

**Comment by elycheea** [comment]
@punnoosewilson Don’t forget to add a v2 PR as well!

@all-contributors add @punnoosewilson for code

**Pull request merged**
