### PR TITLE
docs(NonLinearReading): Update doc after review

### PR DESCRIPTION
**Pull request by paul-balchin-ibm**
Update documentation after review from content designer. All Novice to Pro components will be updated to reflect latest IBM content guidelines.

#### What did you change?

NonLinearReading `mdx` file only.

#### How did you test and verify your work?

Requires sign off from content designer Lynn Harding.

### CODE REVIEW

**Comment by matthewgallo** [comment]
Hey @paul-balchin-ibm, since you mentioned this PR has sign off from Lynn is it ready to be moved from draft?

**Comment by paul-balchin-ibm** [comment]
Sorry, @matthewgallo, I just fixed that statement. It still requires sign off. Sorry about that.

**Comment by paul-balchin-ibm** [comment]
Lynn Harding has approved changes.

**Comment by paul-balchin-ibm** [comment]
@matthewgallo, changes have been approved and PRs for all three doc updates are ready for review. Thanks.

**Pull request merged**
