### PR TITLE
fix: remove spacer column in datagrid

### LINKED ISSUE #3401: All Datagrids have a blank column on the right
## Bug description
The [Datagrid](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage) component includes a blank column on the right for some reason. This doesn't allow our columns to cover the full width of the component for a seamless look.

## Steps to reproduce 
How do we reproduce the error you described above: (ex. below)
1. This can be viewed in any Datagrid story in Storybook
2. Can also be viewed in any Codesandbox with Datagrid. Example from the docs: https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main_v1/examples/carbon-for-ibm-products/Datagrid

## URL/Link of Page
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--basic-usage

https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main_v1/examples/carbon-for-ibm-products/Datagrid

## Expected behavior
There shouldn't be an empty column, the users' columns should be all the component creates.

### Viewing Platform:
 - OS: macOS
 - Browser: Chrome
 - Version: storybook v2.7.0

## Screenshots

https://media.github.ibm.com/user/340510/files/12c37511-8366-4246-8b4d-a5361b48eaeb

### PR DESCRIPTION
**Pull request by davidmenendez**
Closes #3401

### CODE REVIEW

**Comment by matthewgallo** [comment]
I noticed that the table body and table headers don't align together as expected for the `Infinite scroll` and `With virtualized data` stories.

**Comment by elycheea** [comment]
@davidmenendez make sure we also test this on data tables with fewer columns. I remember in our original PR, that caused some issues too where tables would no longer expand to the full width.

(I had to dig deep into my DMs with @matthewgallo to find this.)
image

**Comment by davidmenendez** [comment]
confirmed with @matthewgallo that this fix produces the desired functionality
Screenshot 2024-06-12 at 11 14 08 AM

**Review by kennylam — APPROVED** [review]
LGTM!

**Review by sangeethababu9223 — APPROVED** [review]

**Pull request merged**
