### PR TITLE
feat(Datagrid): add opt out ability for editable cells

### LINKED ISSUE #5379: [Feature Request]: Datagrid doesn't have a way to enable/disable inline edit per cell for specific use cases
### The problem

How we originally have it 

https://github.com/carbon-design-system/ibm-products/assets/10100397/cfa8c8eb-8c08-441b-b430-56a5c3ec2c98

But with data grid, I am not seeing a way where we can say that a specific cell in terms of row to column can be editable or not. This is crucial to our implementation and there isn't a way to do this for DataGrids that I am able to see available

https://github.com/carbon-design-system/ibm-products/assets/10100397/b08ebc84-4713-43b5-b7e3-8bee7124ffa5

### The solution

I think the `data` needs to be segmented to be an object such as 

```
[
    {
        "headerName": "FIRST_NAME",
        "length": 0,
        "isNullable": false,
        "dataType": "VARCHAR",
        "extended": false,
        "scale": undefined,
    },
  ]
 ```
 
 To be something like this 
 ```
[
     { "headerName": "FIRST_NAME", isEditable: true },
     { "length": 0, isEditable: true },
     { "isNullable": false, isEditable: true },
     { "dataType": "VARCHAR", isEditable: true },
     { "extended": false, isEditable: true },
     { "scale": undefined, isEditable: false },
  ]
 ```

### Design link

_No response_

### Links to other materials

_No response_

### Owner/main maintainer(s)

IBM

### Second/backup maintainer(s)

_No response_

### Product/offering

DataStage

### Business priority

High Priority = pressing release

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by matthewgallo**
Closes #5379 

Currently there is no way to opt out of inline editing at the cell level. You can disable editing for an entire column in the table but it isn't possible to have one or more non editable cells in a column with other editable cells. This PR adds that behavior, I added a note in the `EditableCell` story about which cell is non editable for demonstration purposes.

[Example story can be viewed here](https://deploy-preview-5425--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-editablecell--editable-cell-usage-story&globals=viewport:basic).

I also found a bug within editable cell Datagrids where if you attempt to go into edit mode (<kbd>Enter</kbd> key) from  a non-editable cell, the inline edit context's reducer updates the state to be in edit mode. This prevents you from actually going into edit mode within an editable cell because the context thinks we're already in edit mode. I've included this fix here as well since it was a very small change.

#### What did you change?
```
packages/ibm-products/src/components/Datagrid/Datagrid/addons/InlineEdit/InlineEditCell/InlineEditCell.js
packages/ibm-products/src/components/Datagrid/Extensions/EditableCell/EditableCell.docs-page.js
packages/ibm-products/src/components/Datagrid/Extensions/EditableCell/EditableCell.stories.jsx
packages/ibm-products/src/components/Datagrid/useInlineEdit.js
packages/ibm-products/src/components/Datagrid/utils/makeData.js
```
#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Comment by AustinGitHub** [comment]
I checked out the changes on my local env and this works, thank you!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by kennylam — APPROVED** [review]
LGTM!

**Review by emyarod — APPROVED** [review]

**Pull request merged**
