### PR TITLE
fix(datagrid): fixes multiselect for instant update bug

### LINKED ISSUE #5935: [Datagrid]: using MultiSelect filtering with instant update is broken
### Package

Carbon for IBM Products

### Description

i discovered this after discussing a separate issue from slack:

* in order to be more aligned with carbon functionality `MultiSelect` should be passing the entire `event` object to the consumer and not just `{ selectedItems }`

while investigating i also discovered these:

* using `MultiSelect` with batch filtering throws a console warning: `Warning: Cannot update a component ('FilterFlyout') while rendering a different component ('MultiSelect'). To locate the bad setState() call inside 'MultiSelect', follow the stack trace as described in...`
* using `MultiSelect` with instant filtering breaks the app `a.filter is not a function`

### Component(s) impacted

`Datagrid`

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.47

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

ibm products

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-instant&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

for the broken instant update:

go to the [storybook](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-instant&globals=viewport:basic), open the filter, and select an option under one of the multi select drop downs.

for the batch update warning:

*this only appears locally*. run storybook locally and open the [batch update story](http://localhost:3000/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-batch&globals=viewport:basic). select an option from one of the multi select drop downs.

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AlexanderMelox**
Closes #5935 

This PR fixes the error `a.filter is not a function`. Replaced the dropdown filter with multiselect

#### What did you change?
`packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.jsx`

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by davidmenendez — CHANGES_REQUESTED** [review]
i think the underlying issue of using a dropdown needs to be addressed here. there are other examples in storybook of a dropdown being used in the datagrid filter and it's breaking the same way. for example https://deploy-preview-5970--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-filtering-panel--panel-many-checkboxes&globals=viewport:basic

**Comment by AlexanderMelox** [comment]
Thanks David, yeah I've been working on that too. Just wanted to get the stories consistent

**Comment by AlexanderMelox** [comment]
@davidmenendez after further inspection, the reason that was happening was because in the header the filter was multiSelect but the filter in the panel story was dropdown. So nothing to fix, just had to make sure they match. I did double check when they both are dropdown everything works well 

**Status column is multiselect:** https://github.com/carbon-design-system/ibm-products/blob/0c592d2a20f015cf3167344aec8e51ac3f7ea2f9/packages/ibm-products/src/components/Datagrid/utils/FilteringUsage.js#L63

**Doesn't match here:** https://github.com/carbon-design-system/ibm-products/blob/0c592d2a20f015cf3167344aec8e51ac3f7ea2f9/packages/ibm-products/src/components/Datagrid/Extensions/Filtering/Panel.stories.jsx#L297

**Comment by AlexanderMelox** [comment]
Working with dropdown
https://github.com/user-attachments/assets/2f398c5a-e67d-429f-906f-35eb18eb7920

**Comment by AlexanderMelox** [comment]
Also talked to @matthewgallo and agreed to just change them all to multi select

**Review by davidmenendez — APPROVED** [review]
TY!

**Review by sangeethababu9223 — APPROVED** [review]

**Pull request merged**
