### PR TITLE
fix(dataGrid): header scroll issues

### LINKED ISSUE #5948: Datagrid: can't scroll headers
### Package

Carbon for IBM Products

### Description

QA filed a ticket against our product that you can't scroll a table horizontally from the header... i.e. there's no effect when you move the cursor over the header columns, and then move two fingers on the trackpad (or similar action on mobile devices).

From a user's standpoint, I can understand the complaint.

From a development standpoint, I can see neither `useFloatingScroll()` nore `DatagridVirtualBody` have any code to support this.  They only have code to:

```js
// Sync the scrollLeft position of the virtual body to the table header
```

I.E. Code to monitor the `scrollLeft` position of the `<tbody>` and copy it to the `<thead>`. There's no code to allow manually scrolling the `<thead>` nor to copy scroll position from the `<thead>` to the `<tbody>`.

I think to support it you would need to set `overflow-x:auto` on the `<thead>`, but then use the tricks listed in https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll to hide the scrollbar.

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46.0

### Suggested Severity

None

### Product/offering

IKC

### CodeSandbox or Stackblitz example

https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--infinite-scroll&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

It's hard to give a test case for this problem due to all the other bugs.

The [test case listed above](https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid--infinite-scroll&globals=viewport:basic) uses the `withVirtualScroll` flag, but the horizontal scrolling is broken in other ways: notice how you can't see the vertical scrollbar until you scroll all the way to the right.

I also made a [test case for useFloatingScroll()](https://stackblitz.com/edit/github-qcefwb-kgcczw?file=README.md), but it has multiple other problems that need to be fixed first before you can see the problem listed in this ticket.

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #5948

- The width is now dynamically set on window resize. Previously, useIsomorphicEffect used to set the width only during the initial load. the effect didn't used to run on gridRef changes, now we are getting the width from it and passing it as dependency.
- Added a scroll event to the header to sync with the body. Previously, only scrolling the body would sync the header, but now scrolling the header also syncs the body.
- Fixed the last column using the `flex: 1 0 auto` property.

https://github.com/user-attachments/assets/9f9916ab-78c7-41b2-b737-b2d83f10ab38

- Found an unexpected console warning already existing before this pr, and raised #6144 although very minor, raising so we don't lose it.

#### What did you change?
packages/ibm-products-styles/src/components/Datagrid/styles/_datagrid.scss
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridVirtualBody.tsx
packages/ibm-products/src/components/Datagrid/Datagrid/DatagridRow.tsx

#### How did you test and verify your work?
storybook, dev tools touch simulation.

### CODE REVIEW

**Review by amal-k-joy — APPROVED** [review]
Good work

**Review by AlexanderMelox — APPROVED** [review]
LGTM!

**Comment by wkeese** [comment]
Thanks @devadula-nandan, I confirm it works on https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid--infinite-scroll&globals=viewport:basic and https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid--with-virtualized-data&globals=viewport:basic.

Do you have an opinion about @carbon/react's scrolling strategy, which scrolls on the table wrapper via the [stickyHeader](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/DataTable/Table.tsx#L43)... vs. @carbon/ibm-products strategy of scrolling on thead/tbody?

**Comment by devadula-nandan** [comment]
Hi @wkeese, here is my [playground](https://devadula-nandan.github.io/TD-TABLE/?path=/story/example-tdtable--basic&args=stickyHeader:!true;tableHeight:600px;tableWidth:800px&globals=dataTheme:light) while i was experimenting on sticky header with horizontal and vertical scroll, on a constrained table. its not a carbon example but
the div that contains table element needs to have overflow auto and the thead to have sticky and top-0, which i consider an ideal implementation
Screenshot 2024-11-26 at 6 57 01 PM


however carbon's implementation does have sticky and top 0 on thead, but columns doesnt have defined widths like tanstack does, hence we cant get horizontal scrolling to work effectively afaik
Screenshot 2024-11-26 at 7 05 25 PM

and coming to datagrid there is this dependency that got built up on certain implementations within datagrid, to an extent that we need to re architect and could also potentially bring regressions, hence we moved to tanstack-carbon way, in which u can use carbon's datatable features, and u can also bring in your own custom changes.
but i do agree overflow on tbody and thead and syncing them is an overkill

hope this helps

**Comment by wkeese** [comment]
Thanks @devadula-nandan, that all makes sense, although it will personally take me a while to get used to a vertical scrollbar that extends up to the top of the headers.

I wonder why ibm-products Datagrid decided to break ranks with @carbon's DataTable and put separate scrolling on the table body.

But iIn any case, I agree that scrolling on the table itself (or a wrapper around the table) makes sense.  Your playground seems to work perfectly.

**Pull request merged**
