### PR TITLE
chore(examples): remove yarn artifacts

### LINKED ISSUE #5417: [Security]: Dependabot alerts - ip SSRF improper categorization in isPublic
Currently the majority of Dependabot [vulnerability alerts](https://github.com/carbon-design-system/ibm-products/security/dependabot) are due to Yarn artifacts in component examples. These aren't necessary and can be safely removed.

```[tasklist]
### Yarn artifacts to remove in `/examples/`
- [ ] `yarn.lock`
- [ ] `.yarn`
```

### PR DESCRIPTION
**Pull request by kennylam**
Closes #5417 

Remove Yarn artifacts from component examples. These aren't needed and can trigger Dependabot security alerts.

#### What did you change?
Removed `.yarn` and `yarn.lock` in `/examples/`.

#### How did you test and verify your work?

Sample component examples from development branch (no Yarn artifacts):

- Datagrid [Stackblitz](https://stackblitz.com/github/kennylam/ibm-products/tree/chore/examples-remove-yarn-artifacts/examples/carbon-for-ibm-products/Datagrid) [Codesandbox](https://githubbox.com/kennylam/ibm-products/tree/chore/examples-remove-yarn-artifacts/examples/carbon-for-ibm-products/Datagrid)
- Tearsheet [Stackblitz](https://stackblitz.com/github/kennylam/ibm-products/tree/chore/examples-remove-yarn-artifacts/examples/carbon-for-ibm-products/Tearsheet) [Codesandbox](https://githubbox.com/kennylam/ibm-products/tree/chore/examples-remove-yarn-artifacts/examples/carbon-for-ibm-products/Tearsheet)

### CODE REVIEW

**Comment by matthewgallo** [comment]
Can you try running `yarn update-gallery-config` and double check that it doesn't auto generate new yarn artifacts?

**Comment by kennylam** [comment]
Thanks for catching that, I didn't know about that script. I added all example Yarn artifacts to `.gitignore`.

**Comment by kennylam** [comment]
@elycheea Thanks for pointing those out!

**Review by elycheea — APPROVED** [review]
We probably should still run the `yarn update-gallery-config` at some point but let’s address that separately to fix the more pressing issue.

I _think_ @matthewgallo and I might have figured it out but would like to check with @lee-chase first.

**Review by matthewgallo — APPROVED** [review]

**Comment by kennylam** [comment]
> We probably should still run the `yarn update-gallery-config`

I did run it locally. It runs successfully but wasn't the intent of this PR. A separate issue can be created to track that work.

**Comment by elycheea** [comment]
Yep, I’ll open the followup issue. I know Matt and I were able to run it previously but are both getting hit with an error now. 🥹

**Pull request merged**
