### PR TITLE
fix(CreateFullPage): beadcrumbs style issue

### LINKED ISSUE #5452: [createFullPage]: breadcrumbs in header
### Package

Carbon for IBM Products

### Description

Looks like a possible Storybook error with implementing carbon's breadcrumbs. Blue square in the middle of the breadcrumbs in the header
Screenshot 2024-06-10 at 1 13 49 PM

### Component(s) impacted

createfullpage

### Browser

_No response_

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.41.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

n/a

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createfullpage--create-full-page-with-header&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

go to https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-create-flows-createfullpage--create-full-page-with-header&globals=viewport:basic and look at the header

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #5452

Fixed style issue of breadcrumb in header of CreateFullPage

### CODE REVIEW

**Review by devadula-nandan — APPROVED** [review]
LGTM

**Comment by amal-k-joy** [comment]
Hey @matthewgallo,
Looks like we are using carbon component as it is. In carbon story book, this issue is not observed as the default button styles are overridden by styles from class `cds--overflow-menu`. But in `CreateFullPage`, this styles from this same class has got low priority. Can you share your thoughts on this behaviour?

**Comment by matthewgallo** [comment]
These changes should actually be applied to the `SimpleHeader` component. It is a simplified version of the `PageHeader` and that's where the style issues are coming from here. It had a corresponding style file (`_simple-header.scss`) where these fixes can be applied.

**Review by matthewgallo — CHANGES_REQUESTED** [review]
See comment around making these changes within `_simple-header.scss`.

**Comment by amal-k-joy** [comment]
> See comment around making these changes within `_simple-header.scss`.

@anamikaanu96 ,
I could see lot of carbon styles was added redundantly to the component due to the below style import in the `_storybook-styles.scss` file of `createFullPage`. This changed the priority of the styles which caused this issue. You can see styles for `.cds--btn--primary` is added twice.
`@use '@carbon/styles/scss/components/ui-shell' as *;`

 I think we can remove this line or add this fix to the `_storybook-styles.scss`  file as this issue should be specific to storybook.
@matthewgallo , Can you share your thoughts here. Shall we remove this style import.?

**Comment by matthewgallo** [comment]
I agree, lets just remove the ui-shell style import from `_storybook-styles.scss` for `CreateFullPage`. It's causing specificity issues and is already imported when we import the base Carbon styles from `packages/core/.storybook/carbon.scss`.

**Pull request merged**
