### PR TITLE
fix: (Datagrid) filters fix

### PR DESCRIPTION
**Pull request by xmannyxfreshx1**
Closes https://github.com/carbon-design-system/ibm-products/issues/4538

#### What did you change?
- This replaces the use of `localDispatch` inside `applyFilters()` with local state. Functionally, it's still applying those filters when `isFetching` is `true`.
- Also, `isFetching` is now simulated when using the refresh control in the filter storybook examples.

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Comment by xmannyxfreshx1** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by anamikaanu96** [comment]
Hi @xmannyxfreshx1 Thank you for your contribution!

Looks like this issue is addressed on this [PR](https://github.com/carbon-design-system/ibm-products/pull/6031). Can you please confirm.

**Comment by xmannyxfreshx1** [comment]
Hi, @anamikaanu96 just took a look at that PR and yep it appears that it resolves the issue this PR was trying to fix. We can close both this PR and the tagged issue. Thanks

**Comment by xmannyxfreshx1** [comment]
The only other thing I would request is if we could add these changes
Screenshot 2024-09-19 at 11 41 50 AM
to the filtering storybook examples. These changes reflect a more real world usage of the refresh button where the `isFetching` state is changed.

**Comment by amal-k-joy** [comment]
> The only other thing I would request is if we could add these changes Screenshot 2024-09-19 at 11 41 50 AM to the filtering storybook examples. These changes reflect a more real world usage of the refresh button where the `isFetching` state is changed.

Hey @xmannyxfreshx1 ,
Thanks for confirming that the original issue is fixed.

There seems to be a console error for other stories where `setIsFetching` is not passed and used batch actions. 
I have feeling like `isFetching` can be managed by the adopter itself. 
@davidmenendez , can you share your thoughts on this ?
image

**Comment by amal-k-joy** [comment]
Closing this PR as user confirmed original  issue is already fixed.

**Pull request closed without merging**
