### PR TITLE
fix(Dataspreadsheet): selection area behavior fixed

### PR DESCRIPTION
**Pull request by AustinGitHub**
Closes #

https://github.com/carbon-design-system/ibm-products/issues/5262
https://github.com/carbon-design-system/ibm-products/issues/5484

#### What did you change?

I made it so we check if there is a column we are holding and dragging so the mouse up behavior can work as intended. This also fixes the issue where when we do mouseUp we don't persist the `headerCellHoldActive` of true when it should be false. 

I also fixed the issue where the callback function was not logging all the selections when the selection area changed. There is another condition we need to also check for. I checked original behaviors and I am not seeing any regressions. Thanks!

#### How did you test and verify your work?

Storybook 

https://github.com/carbon-design-system/ibm-products/assets/10100397/86f5f60c-2ca1-4203-9a60-644f0e999907

### CODE REVIEW

**Comment by AustinGitHub** [comment]
Going to try and add fix for this https://github.com/carbon-design-system/ibm-products/issues/5484 in here as well. I was debugging separate and realized it would be easier to add in this PR.

**Comment by AustinGitHub** [comment]
https://github.com/carbon-design-system/ibm-products/assets/10100397/7e4f1455-778b-4d7b-abf0-0af1e5bec52c

I also fix this issue https://github.com/carbon-design-system/ibm-products/issues/5484

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Nice! One thing I notice is that the selection area if you select an entire column and then reorder it, the selection area is lost. Can you take a look at this so that if you have a column selected (selection area exists for the entire column) it is still included after moving the column?

**Comment by AustinGitHub** [comment]
Sure

**Comment by matthewgallo** [comment]
https://github.com/carbon-design-system/ibm-products/pull/5420 was merged which fixes the Mend check that was failing.

**Review by matthewgallo — APPROVED** [review]

**Comment by AustinGitHub** [comment]
oh, I had only resolved the code conflict

**Review by davidmenendez — APPROVED** [review]

**Review by matthewgallo — APPROVED** [review]

**Pull request merged**
