### PR TITLE
ci: VRT setup configuration in workflow

### LINKED ISSUE #5236: Setup VRT
create a branch on main, and add percy integration code taking reference from https://github.com/carbon-design-system/ibm-products/tree/feat/percy-integration, test the integration by making few test prs on this branch, if there is any false reporting, exclude the stories, until we fix/skip the conflicts responsible for false reporting

https://www.browserstack.com/docs/percy/integrate/storybook

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #5236 

implements vrt in ci

#### What did you change?
added a vrt runner in ci.yml
added a new config file .percy.yml

#### How did you test and verify your work?
branch on main, test prs, percy dashboard, yarn run visual-snapshot

### CODE REVIEW

**Comment by devadula-nandan** [comment]
@kennylam, @matthewgallo, @elycheea The PR is ready for review. Please take a look when you have time. Thanks!

**Comment by devadula-nandan** [comment]
An interesting observation is that many of our components—such as the tearsheet, side panel, notifications panel, and modals have a default closed state. To fully leverage this integration, it would be beneficial to set them to a default open state. In contrast, most components in the core library are configured with a default open state.

**Comment by elycheea** [comment]
@devadula-nandan That’s a good point which also means all those accessibility tests also require the extra steps to show the open states. 🤔

**Review by kennylam — DISMISSED** [review]
This looks great!

**Review by kennylam — APPROVED** [review]

**Review by matthewgallo — APPROVED** [review]
🎉 awesome work, excited to have this added!

**Comment by devadula-nandan** [comment]
@kennylam @matthewgallo , the vrt checks for prs made on main are failing with token not found (https://github.com/carbon-design-system/ibm-products/actions/runs/11853707335/job/33034370787?pr=6440#step:7:18), im suspecting the token is not scoped to main branch, but couldn't verify, as i don't have complete access to this repo settings, could you pls check it? thanks.

**Pull request merged**
