### PR TITLE
feat(dataspreadsheet): option for read only table + option for disable column swapping

### LINKED ISSUE #5591: [Feature Request]: Dataspreadsheet - Allow user to disable column swapping drag/drop
### The problem

User isn't able to disable column drag and drop. 

Reason for this: User might not want to drag drop columns and/or they might accidentally do it when table shouldn't allow them

### The solution

On the data spreadsheet properties, allow custom attribute boolean which default will be true but if set to false the drag/drop of columns can be disabled. 

### Design link

_No response_

### Links to other materials

_No response_

### Owner/main maintainer(s)

IBM

### Second/backup maintainer(s)

_No response_

### Product/offering

IBM

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### LINKED ISSUE #5592: [Feature Request]: Dataspreadsheet - Add readonly option to pass through to make table non-editable
### The problem

Right now there isn't a way to make table non-editable

### The solution

Add pass through option so table can switch states so when it is editable we can make it non-editable

### Design link

_No response_

### Links to other materials

_No response_

### Owner/main maintainer(s)

IBM

### Second/backup maintainer(s)

_No response_

### Product/offering

Datastage

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AustinGitHub**
Closes #5592
Closes #5591

#### What did you change?

I added optional parameters to pass through to disable column swapping and to make the table read only if user wants it to be this way

#### How did you test and verify your work?

Storybook

https://github.com/carbon-design-system/ibm-products/assets/10100397/847802f2-fc0c-438c-9417-57d24e32678f

### CODE REVIEW

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Looks good, just one suggestion here. Can you use the default storybook controls as opposed to inline checkboxes within the story to toggle these props?

If you pass these props from
```jsx
withDifferentOptions.args = {
  readOnlyTable: true,
  disableColumnSwapping: true,
  selectAllAriaLabel: 'Select all',
  spreadsheetAriaLabel: 'Example data spreadsheet',
  totalVisibleColumns: 5,
}
```
you'll be able to toggle them from the "Controls" tab within storybook.

**Comment by AustinGitHub** [comment]
Sure

**Comment by matthewgallo** [comment]
I also think that the cursor should remain `pointer` when a header is selected and column swapping is disabled as opposed to `grab`.

**Comment by AustinGitHub** [comment]
Hmm, it was working as pointer for me yesterday but I know what you mean because I also saw weird grab cursor still in some cases. I will check on it

**Comment by AustinGitHub** [comment]
https://github.com/carbon-design-system/ibm-products/assets/10100397/8c914cbd-756d-41e1-a222-f2008b40be92


Screenshot 2024-06-26 at 8 08 49 AM


This is fixed, thanks!

**Review by davidmenendez — APPROVED** [review]

**Pull request merged**
