### PR TITLE
fix: Return focus to launcher button

### PR DESCRIPTION
**Pull request by makafsal**
Contributes to #5014 

#### What did you change?
Implemented `launcherButtonRef` in both Tearsheet and SidePanel components

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by davidmenendez — CHANGES_REQUESTED** [review]
this looks good. can you include this change in a storybook story so the functionality can be demonstrated?

**Comment by makafsal** [comment]
> this looks good. can you include this change in a storybook story so the functionality can be demonstrated?

Included in storybook.

**Review by davidmenendez — CHANGES_REQUESTED** [review]
this looks good! can you just update / add tests for this new code?

**Review by davidmenendez — APPROVED** [review]
TY!

**Comment by makafsal** [comment]
@davidmenendez Added test for both SidePanel and Tearsheet.

**Review by davidmenendez — APPROVED** [review]

**Review by amal-k-joy — DISMISSED** [review]

**Review by davidmenendez — APPROVED** [review]

**Review by amal-k-joy — APPROVED** [review]

**Pull request merged**
