### PR TITLE
feat: community package init

### PR DESCRIPTION
**Pull request by davidmenendez**
for #3814

### CODE REVIEW

**Comment by davidmenendez** [comment]
@matthewgallo & @lee-chase would love y'all's input!

**Comment by matthewgallo** [comment]
Yes! So I was wondering why we need a storybook setup for this package? The other packages (when there were others ie `cdai` and `security`) all were included in our main storybook, from `packages/core` so there is no need to include a storybook config for individual packages. This could clean things up and reduce the config that you've included. A good example to maybe take a look at is `@carbon/ibm-products-styles` since @lee-chase recently created that new package.

**Comment by davidmenendez** [comment]
> Yes! So I was wondering why we need a storybook setup for this package? The other packages (when there were others ie `cdai` and `security`) all were included in our main storybook, from `packages/core` so there is no need to include a storybook config for individual packages. This could clean things up and reduce the config that you've included. A good example to maybe take a look at is `@carbon/ibm-products-styles` since @lee-chase recently created that new package.

oh ok i wasn't aware we had a shared storybook config. that definitely makes sense. the stories here can definitely reside in a section called `community` 👍

**Comment by davidmenendez** [comment]
now that i know i don't need to include storybook i'm going to just redo this because it appears to be more difficult to remove it as opposed to starting fresh

**Pull request closed without merging**
