### PR TITLE
chore: deprecate edit and update

### LINKED ISSUE #6321: deprecate edit and update
- [x] edit side panel
- [x] edit fullpage
- [x] edit tearsheet
- [x] edit tearsheetnarrow
- [x] edit update cards

### Deprecation steps
https://github.com/carbon-design-system/ibm-products/pull/6223/files

1. add deprecation flag in the components
2. document deprecation stuff like migration, story docs, ts deprecation, 
3. updating tests

### Air table update:
Update [Airtable](https://airtable.com/appY30x3q9FcdIcL1/shrbZABYNrL5A7CUx) to track status when each component moves from 'To be deprecated' to 'Deprecated' at the time of deprecation

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #6321 

deprecates below components

edit side panel
edit fullpage
edit tearsheet
edit tearsheetnarrow
edit update cards

#### What did you change?
added deprecation annotation, deprecated the component, and added a notice in story docs, and expected consol warning in test.

packages/ibm-products/src/components/CreateFullPage/_storybook-styles.scss
packages/ibm-products/src/components/EditFullPage/EditFullPage.stories.jsx
packages/ibm-products/src/components/EditFullPage/EditFullPage.test.js
packages/ibm-products/src/components/EditFullPage/EditFullPage.tsx
packages/ibm-products/src/components/EditSidePanel/EditSidePanel.stories.jsx
packages/ibm-products/src/components/EditSidePanel/EditSidePanel.test.js
packages/ibm-products/src/components/EditSidePanel/EditSidePanel.tsx
packages/ibm-products/src/components/EditTearsheet/EditTearsheet.test.js
packages/ibm-products/src/components/EditTearsheet/EditTearsheet.tsx
packages/ibm-products/src/components/EditTearsheet/preview-components/MultiFormEditTearsheet.js
packages/ibm-products/src/components/EditTearsheetNarrow/EditTearsheetNarrow.stories.jsx
packages/ibm-products/src/components/EditTearsheetNarrow/EditTearsheetNarrow.test.js
packages/ibm-products/src/components/EditTearsheetNarrow/EditTearsheetNarrow.tsx
packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.stories.jsx
packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.test.js
packages/ibm-products/src/components/EditUpdateCards/EditUpdateCards.tsx
and respective avt files

#### How did you test and verify your work?
storybook, yarn test

### CODE REVIEW

**Review by matthewgallo — COMMENTED** [review]
I think we should place these under the `Deprecated` section in storybook with the HTTP error components.

Also, we should include the `@deprecated` JSDoc tag in the components so that they receive a strike through when they're used.
Screenshot 2024-11-11 at 2 32 04 PM

**Comment by matthewgallo** [comment]
I just thought of this when reviewing @makafsal's PR for deprecating some of the security components, you could cleanup the stories files by using the `decorators` property from the default story export, so you can wrap each story with the `Annotation` component.

**Comment by devadula-nandan** [comment]
> I just thought of this when reviewing @makafsal's PR for deprecating some of the security components, you could cleanup the stories files by using the `decorators` property from the default story export, so you can wrap each story with the `Annotation` component.

@matthewgallo done

**Review by AlexanderMelox — APPROVED** [review]
LGTM!

**Review by davidmenendez — APPROVED** [review]
LGTM!

**Pull request merged**
