### PR TITLE
fix(pageheader): compensate the width of the overflow menu

### LINKED ISSUE #5806: PageHeader: `actionBarItems` are put into overflow menu even when there is enough space to display outside of overflow
### Package

Carbon for IBM Products

### Description

It appears that the last `actionBarItem` is being put inside an overflow menu even when there is enough space to display it outside of an overflow menu. The expectation is that the action bar items are only included in an overflow when there isn't enough space to be displayed outside of the menu.

### Component(s) impacted

Page header

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.46.0

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

N/A

### CodeSandbox or Stackblitz example

https://deploy-preview-5696--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--demo&args=pageActions:6&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

[Visible in this story](https://deploy-preview-5696--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-page-header-pageheader--demo&args=pageActions:6&globals=viewport:basic)

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by AlexanderMelox**
Closes #5806 

This PR fixes the issue of the overflow menu hiding actions even when there is enough space. I don't know if this is the best fix for it maybe @lee-chase can help out. 

#### What did you change?
packages/ibm-products/src/components/PageHeader/PageHeader.tsx

#### How did you test and verify your work?
By opening the build and resizing the browser

### CODE REVIEW

**Review by lee-chase — APPROVED** [review]
Looks good to me, only concern would be the button size changing.

**Comment by matthewgallo** [comment]
Can you see if you can send back a ref to the overflow menu from the `ActionBar`'s `onWidthChange` callback? Then in `PageHeader`'s `handleActionBarWidthChange` you can check for the width of the returned `ref`'.

**Comment by AlexanderMelox** [comment]
> Can you see if you can send back a ref to the overflow menu from the `ActionBar`'s `onWidthChange` callback? Then in `PageHeader`'s `handleActionBarWidthChange` you can check for the width of the returned `ref`.

Used a ref for dynamic width

**Review by devadula-nandan — APPROVED** [review]

**Review by matthewgallo — CHANGES_REQUESTED** [review]
While we're still using both TS types and prop types, can you update the the prop types for the components that now have new props?

**Comment by AlexanderMelox** [comment]
Makes sense, added the proptypes

**Review by matthewgallo — APPROVED** [review]

**Review by davidmenendez — APPROVED** [review]

**Review by devadula-nandan — APPROVED** [review]

**Comment by devadula-nandan** [comment]
can you check `CI / avt-runner (3) (pull_request)`? it reported as pass, but the page header avt's failed, which needs to be re-aligned after this fix. maybe in a separate issue?

**Pull request merged**
