### PR TITLE
feat: Side panel ai enhancements

### PR DESCRIPTION
**Pull request by lee-chase**
Contributes to #3752

https://github.com/carbon-design-system/carbon-for-ai/issues/16

Add AI slug and background

#### What did you change?

Side Panel to accommodate the slug

#### How did you test and verify your work?

Storybook

### CODE REVIEW

**Comment by lee-chase** [comment]
Currently unable to build preview, waiting on Carbon patch release.

**Review by matthewgallo — CHANGES_REQUESTED** [review]
There are some files included in this PR that don't seem related to side panel changes. Can we remove those?

- .yarn/cache/*
- carbon-react-1.42.1.tgz
- InlineTip
- SteppedAnimatedMedia
- yarn.lock

**Comment by lee-chase** [comment]
> There are some files included in this PR that don't seem related to side panel changes. Can we remove those?
> 
> * .yarn/cache/*
> * carbon-react-1.42.1.tgz
> * InlineTip
> * SteppedAnimatedMedia
> * yarn.lock

The lock file has been usurped by the Carbon upgrade last week, not sure why merge does not deal with this.

**Review by matthewgallo — APPROVED** [review]

**Comment by matthewgallo** [comment]
@elycheea good point, the slug does appear to visually float when there is not a title. I think it's still optional unless there is `labelText` provided, unless that was changed 🤔

**Pull request merged**
