### PR TITLE
fix(Saving): reversed icons for default state (save) and success state (checkmark)

### PR DESCRIPTION
**Pull request by MriduMohan**
Contributes to #2849

#### What did you change?
Reversed the the icons shown for  default state and success state to save and checkmark icons respectively.

#### How did you test and verify your work?
storybook

### CODE REVIEW

**Comment by MriduMohan** [comment]
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> I have read the DCO document and I hereby sign the DCO.
> 
> **MriduMohan** seems not to be a GitHub user. You need a GitHub account to be able to sign the DCO. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

**Comment by MriduMohan** [comment]
> I have read the DCO document and I hereby sign the DCO.

**Comment by MriduMohan** [comment]
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> I have read the DCO document and I hereby sign the DCO.
> 
> **MriduMohan** seems not to be a GitHub user. You need a GitHub account to be able to sign the DCO. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

**Comment by MriduMohan** [comment]
recheck

**Comment by elycheea** [comment]
@MriduMohan Thanks for submitting your first PR with us! It looks like the email associated with your commit does not match the one on your GitHub account. I think the DCO should work once you add your IBM address to your public GitHub account! (Although you might still need to comment `recheck` again once you add it.)

**Comment by MriduMohan** [comment]
recheck

**Comment by MriduMohan** [comment]
recheck

**Comment by MriduMohan** [comment]
@elycheea , could you please tell me how to resolve the check. I tried the ways you told above. It still doesn't work.

**Review by elycheea — COMMENTED** [review]
Thanks for contributing this fix!

Also caught a small alignment issue when testing this —

image

The loading icon is not vertically centered. We can open this as a separate bug but also would like to know if you’d like to include this since it’s noticeable here.

**Review by elycheea — APPROVED** [review]

**Pull request merged**
