### PR TITLE
fix(pageHeader): menu button overflow issue on small screens

### LINKED ISSUE #6415: [BUG]: Firefox Pageheader overflow issue
### Package

Carbon for IBM Products

### Description

While working on a project, testers in our team
noticed difference in overflow styling between firefox and chrome for PageHeader component (imported via '@carbon/ibm-products') - specifically action bar.

### Component(s) impacted

PageHeaderImage

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.11.2

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM PageHeader component

### CodeSandbox or Stackblitz example

https://stackblitz.com/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/PageHeader?file=src%2FExample%2FSamplePage%2FSamplePage.jsx

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by devadula-nandan**
Closes #6415 

fixes menu button overflow issue in firefox in small screen

#### What did you change?
packages/ibm-products-styles/src/components/PageHeader/_page-header.scss

#### How did you test and verify your work?
storybook, firefox

### CODE REVIEW

**Review by davidmenendez — APPROVED** [review]
LGTM.

small note: in the future, when fixing visual bugs, can you provide a before and after? just easier for the reviewer to verify 👍 

before:

Screenshot 2024-11-26 at 1 46 13 PM

after:

Screenshot 2024-11-26 at 1 46 10 PM

**Review by sangeethababu9223 — APPROVED** [review]
LGTM

**Comment by devadula-nandan** [comment]
Hi @davidmenendez , @sangeethababu9223 .
could you pls review the visual changes in percy as well?

Screenshot 2024-11-27 at 11 33 13 AM

**Comment by sangeethababu9223** [comment]
> Hi @davidmenendez , @sangeethababu9223 . could you pls review the visual changes in percy as well?
> 
> Screenshot 2024-11-27 at 11 33 13 AM

Approved.

**Pull request merged**
