### PR TITLE
refactor: convert ToolbarButton to typescript

### PR DESCRIPTION
**Pull request by matassp**
Contributes to #4276 

Converts ToolbarButton component to use typescript, no visual component changes just refactoring.

Small PR to begin contributing with, I'll add more types if this goes well.

#### What did you change?
Converted `ToolbarButton` component to typescript.
Updated contribution docs to include an up to date link.

#### How did you test and verify your work?
Checked storybook and ran unit tests locally.

### CODE REVIEW

**Comment by matassp** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by matassp** [comment]
recheck

**Comment by matassp** [comment]
recheck

**Review by matthewgallo — APPROVED** [review]
Thanks for contributing @matassp 🥳

**Pull request merged**
