### PR TITLE
fix(Datagrid): sticky row action column solid background

### PR DESCRIPTION
**Pull request by makafsal**
Contributes to #4038 

DataGrid: Sticky row action column background changed to solid `$layer-01`

#### What did you change?
`packages/ibm-products-styles/src/components/Datagrid/styles/_useStickyColumn.scss`

```
.#{variables.$block-class}__right-sticky-column-cell {
  background-color: $layer-01;
}
```
#### How did you test and verify your work?
Manually tested in Storybook

### CODE REVIEW

**Comment by elycheea** [comment]
@makafsal We just took a look during our office hours and saw some issues — when the first column is frozen, we also notice the same transparency. (Both left and right columns can be frozen.)

Additionally, @SeonyuK found a related issue with the header rows where on hover, they also appear transparent. Do you mind including this as part of this PR as well.

image

**Review by davidmenendez — APPROVED** [review]

**Review by elycheea — CHANGES_REQUESTED** [review]
We also need to apply this to the `.#{variables.$block-class}__checkbox-cell-sticky-left` and `.#{variables.$block-class}____left-sticky-column-cell`.

We also need to fix this for frozen header rows on hover ...

image

(Quick glance, it looks like it comes from `...resizableColumn:hover` ...

**Comment by makafsal** [comment]
@elycheea @SeonyuK - Resolved issues in the column headers and checkbox cells.

```
.#{variables.$block-class}__left-sticky-column-cell {
  background-color: $layer-01;
}
```

```
.#{$block-class}__resizableColumn:hover {
  background-color: $layer-selected-hover;
}
```

```
.#{$block-class}__head-select-all.#{$block-class}__checkbox-cell.#{$block-class}__checkbox-cell-sticky-left {
        background-color: $layer-01;
}
```

```
 &.#{$block-class}__checkbox-cell-sticky-left {
        background-color: $layer-01;
 }
```

**Review by elycheea — APPROVED** [review]
🙌

**Comment by elycheea** [comment]
@all-contributors add @makafsal for code

**Pull request merged**
