### PR TITLE
feat: add welcome animation

### PR DESCRIPTION
**Pull request by elycheea**
Reopening on behalf of @kristastarr 
Replaces #3164 

> Please do not merge yet - need to add query for prefers-reduced-motion to show static animation for users who prefer reduced motion 
> 
> #### What did you change?
> 
> - Added Lottie animation to welcome tab of Storybook
> - Added media queries for animation 
> 
> #### How did you test and verify your work?
> Viewed in Chrome at many different screen sizes using Chrome devtools responsive tool

### CODE REVIEW

**Comment by elycheea** [comment]
@kristastarr moved it back to draft since your previous PR was in this state. I think the last merge from `main` caused some issues. I checked out your PR from the commit before and was able to update without issue (hence the new PR).
It’s now from my fork though, but click the `ready for review` if we actually are ready. :D

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Looks great, I just think the `lottie-web` dependency belongs in `packages/core/package.json` instead of the root level `package.json`.

**Comment by mikeolasov** [comment]
@kristastarr Looks good.

**Review by matthewgallo — APPROVED** [review]
🎉

**Pull request merged**
