### PR TITLE
fix(NotificationPanel): option to remove dnd

### PR DESCRIPTION
**Pull request by Ratheeshrajan**
Contributes to #2975 

Option to remove 'Do not Disturb' label and toggle from the notification panel by removing `onDoNotDisturbChange`.

#### What did you change?
Checking if there is `onDoNotDisturbChange` func available or not to render 'Do not Disturb'
#### How did you test and verify your work?
1. Storybook
2. Comment out `onDoNotDisturbChange: action('Toggled to do not disturb'),` from `NotificationsPanel.stories.js`

### CODE REVIEW

**Review by lee-chase — APPROVED** [review]

**Review by lee-chase — CHANGES_REQUESTED** [review]
Can we mark the proptype as optional and ensure storybook is capable of displaying this state.

**Comment by Ratheeshrajan** [comment]
> Can we mark the proptype as optional and ensure storybook is capable of displaying this state.

Introduced an optional prop `showDoNotDisturb` 
image
Hope this works.

**Comment by lee-chase** [comment]
Sorry @Ratheeshrajan I think the preferred solution is to do as you did initially and comment the propTypes as follows and not add the additional property. 

```
  /**
   * Optional: function that returns the current selected value of the disable notification toggle
   */
  onDoNotDisturbChange: PropTypes.func,
```

You could also update the propTypes for the comments for any related properties `doNotDisturbLabel` and `doNotDisturbDefaultToggled` to state if/when they are required.

**Review by lee-chase — CHANGES_REQUESTED** [review]
See comment.

**Comment by Ratheeshrajan** [comment]
@lee-chase reverted back to the initial solution.

**Pull request merged**
