### PR TITLE
feat: add `customSvg` prop to `FullPageError`

### LINKED ISSUE #5975: [Feature Request]: Add custom svg slot on `FullPageError` for custom error pages
### The problem

I want to create a custom `FullPageError` for different error codes other than 404 and 403, and I want to use a different svg for each one.

### The solution

Add a new optional custom slot/parameter for svgs that can be used when the kind is `custom`. If not provided, then it will use the existing behavior

### Design link

_No response_

### Links to other materials

_No response_

### Owner/main maintainer(s)

.

### Second/backup maintainer(s)

_No response_

### Product/offering

IBM Event Endpoint Management

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by stefan-cooper**
Closes #5975 

This PR adds a new optional prop to the `FullPageError` component. It allows you to provide a custom JSX/svg instead of the generic svg for 'custom' full page errors

#### What did you change?

I added a new optional property that is used when `kind` is `custom` and `customSvg` is defined. Otherwise, it will use the original behavior.

#### How did you test and verify your work?

I added a test that uses the 403 svg on the 'custom' kind and verified that it was found.

### CODE REVIEW

**Comment by stefan-cooper** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by stefan-cooper** [comment]
recheck

**Comment by devadula-nandan** [comment]
waiting for issue triaging/design opinion as a first pass.

**Review by AlexanderMelox — APPROVED** [review]
Looks good to me, like @devadula-nandan said lets see what design says

**Review by davidmenendez — APPROVED** [review]

**Comment by davidmenendez** [comment]
@stefan-cooper looks like the unit tests are failing. can you take a quick look locally?

**Comment by elycheea** [comment]
Closing as not planned as referenced in https://github.com/carbon-design-system/ibm-products/issues/5975#issuecomment-2353076256.

**Pull request closed without merging**
