### PR TITLE
fix: vertical alignment in larger row heights

### PR DESCRIPTION
**Pull request by Tanush-J**
Contributes to #3548

After this content is top-aligned in `Extra large` row height.

#### What did you change?

Changed the default value of `verticalAlign` property from `'center'` to `'top'` in DatagridContent.js file.

#### How did you test and verify your work?

https://github.com/carbon-design-system/ibm-products/assets/75922615/20d660ed-bf2b-40e6-a118-411d02064281

### CODE REVIEW

**Comment by Tanush-J** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Thanks for looking at this @Tanush-J! There may be some missing styles, if you look at one of the stories for the Datagrid that includes selectable rows, you'll notice that the checkbox and the row content do not align.

See issue below:
image

You can use the [Batch action story](https://deploy-preview-3568--carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-datagrid-canary--batch-actions) as an example to view this behavior.

Instead of changing `verticalAlign` default value to `top`, I think it would be better to do this by targeting the xl class, something like:
```scss
.cds--data-table--xl .c4p--datagrid__head,
.cds--data-table--xl .c4p--datagrid__carbon-row {
  align-items: flex-start;
}
```

This could be added to `_RowSizeDropdown.scss`, replacing `cds--data-table` and `c4p--datagrid` with the appropriate sass variables.

**Comment by matthewgallo** [comment]
Yes, you're correct. There will be some more styling changes required given the different variations of this component.

**Comment by matthewgallo** [comment]
Hey @Tanush-J, we had to address this issue in a separate PR. We'd welcome future contributions!

**Pull request closed without merging**
