### PR TITLE
fix(NotificationPanel): add missing role

### LINKED ISSUE #5448: [Notifications Panel]: might be missing a role
### Package

Carbon for IBM Products

### Description

Possibly missing a "role" as there is currently no role applied

If we consider this to be a "dialog", it would need a focus trap added.

### Component(s) impacted

notifications Panel

### Browser

_No response_

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.41.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Product/offering

N/A

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-notifications-notificationspanel--default&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
Closes #5448

Add missing a role to the Notification Panel.

#### What did you change?
Added `role="dialog"` to the panel and focus trap for it.
(Had to disable `jsx-a11y/no-noninteractive-element-interactions` for dialog element to allow the use of `Escape` key for closing the panel)

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Comment by devadula-nandan** [comment]
hi @sangeethababu9223 ,
few things i observed
1) When the dialog opens, the focus should automatically move to the dialog.(which announces to screenreader that the dialog is open)
2) when dialog is closed with escape key, the focus should return to the triggering button
3) closing with escape key isn't showing exit animation

**Review by devadula-nandan — DISMISSED** [review]
Although I am not certain where the initial focus should be placed when the dialog is opened—whether on the dialog itself, the 'Dismiss All' button, or the first notification—we can discuss this in our QA meeting to determine the expected behavior. The same applies to focus returning to the triggering button (this is left for QA audit).

Additionally, closing the panel with the Escape key does not show the exit animation, which can be addressed in a later issue.

**Comment by sangeethababu9223** [comment]
> the code looks good! one last thing though, can you provide some testing for this functionality?

Thanks @davidmenendez.
I've added test cases for `esc` key and focus trap.

**Review by davidmenendez — APPROVED** [review]
LGTM! thanks for all your hard work and patience 👍

**Review by devadula-nandan — APPROVED** [review]

**Pull request merged**
