### PR TITLE
fix(datagrid): hidden columns included in search results

### LINKED ISSUE #5509: [Datagrid]: Hidden columns are included in search results.
### Package

Carbon for IBM Products

### Description

Hidden columns are included in the search.

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.39.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

na

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic

### Steps to reproduce the issue (if applicable)

Go here https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-columncustomization--column-customization-usage-story&globals=viewport:basic

1. Unselect all columns in custome cilumn view and leave rowID as visible.
2. Type "apples" in the search box.
3. One item appears in the search.

I would expect that hidden columns are not included in the search

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by sangeethababu9223**
Closes #5509

Hidden columns are included in search results. 

#### What did you change?
`packages/ibm-products/src/components/Datagrid/Extensions/ColumnCustomization/ColumnCustomization.stories.jsx`
Updated `columns` prop to include `disableGlobalFilter: true` for hidden columns in story.

#### How did you test and verify your work?
Storybook

### CODE REVIEW

**Review by AlexanderMelox — CHANGES_REQUESTED** [review]
Like we talked previously this week, there might be a better way to do this

**Comment by sangeethababu9223** [comment]
> Like we talked previously this week, there might be a better way to do this

Hey @AlexanderMelox ,
I did some research following our meeting, and the only alternative I could find was writing a custom filter function. I also found a similar [discussion topic](https://github.com/TanStack/table/discussions/2373) in the React Table repository, but it doesn’t have a solution yet. There might be a better approach in TanStack version 8—I can look into this further if needed for a future implementation. This workaround is the best I could find at the moment.

However if I've missed something please let me know.

**Comment by AlexanderMelox** [comment]
Okay I went through it, I believe the only thing @matthewgallo  mentioned was using `await wait(0)` instead of setTimeout, but i would double check with him

**Review by AlexanderMelox — APPROVED** [review]

**Review by matthewgallo — APPROVED** [review]
Lets make a note about this being an area where the changes in `@tanstack/react-table` v8 make this functionality much easier to implement.

**Pull request merged**
