### PR TITLE
fix: check for document for matchmedia

### PR DESCRIPTION
**Pull request by davidmenendez**
Contributes to #4966 

* adds some utility functions to check for `window` and `document`
* adds a hook to check users reduced motion preferences 
* updated `NotificationsPanel` to use the new `usePrefersReducedMotion` hook to avoid SSR issues

### CODE REVIEW

**Comment by davidmenendez** [comment]
for some reason using `usePrefersReducedMotion` breaks in `SidePanel`. additional time should be spent here to take a look at the code.

**Review by matthewgallo — CHANGES_REQUESTED** [review]
Can the options in the callback passed to `mockImplementation` be stored in a separate file and imported since it looks like the same options are used across multiple test files? Really like that we have a shared hook for this now 🎉

**Comment by davidmenendez** [comment]
> Can the options in the callback passed to `mockImplementation` be stored in a separate file and imported since it looks like the same options are used across multiple test files?

good call. i was thinking about this in passing, but didn't bother to try to implement it because i was worried something like this might adversely affect other tests. i'll give it a shot.

**Comment by davidmenendez** [comment]
@matthewgallo as i had initially suspected trying to include the match media mock in the setup breaks a whole bunch of tests. i think for now we leave it as be for the sake of getting the original fix out and then we open another issue to fix the jest setup specifically.

**Review by matthewgallo — APPROVED** [review]

**Pull request merged**
