### PR TITLE
fix(OptionsTile): fix styling of summary and chevron when nesting OptionsTile

### LINKED ISSUE #5560: [OptionsTile]: Nested options tile does not render chevron and summary correctly
### Package

Carbon for IBM Products

### Description

When nesting an OptionsTile into a parent OptionsTile, the nested options tile exhibits the following problems:
- When the nested options tile is collapsed, its summary is not visible. The expected behavior is that when a nested options tile is collapsed, that the summary is visible.

- When the nested options tile is collapsed, its chevron is pointing upwards (instead of downwards). Since the chevron does not change between collapsed and expanded, the animation between the two states is also not visible.
  
image

The screen-shot above has been created using the following code:

```jsx
<OptionsTile
  summary="This is the parent"
  title="Parent options tile"
>
  <OptionsTile
    summary="Summary of the nested options tile"
    title="Nested options tile"
  >
    <p>
      Lorem ipsum dolor sit amet consectetur adipisicing elit.
    </p>
  </OptionsTile>
</OptionsTile>
```

### Component(s) impacted

OptionsTile

### Browser

Chrome, Safari

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.43.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM z

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-pjtyuj?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

_No response_

### Release date (if applicable)

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by lakeside76**
Closes #5560

Change selectors for the OptionTile's summary and chevron elements to use BEM modifiers.

#### What did you change?

change the selectors for the CSS rules applicable to summary and chevron to use BEM modifiers, instead of looking at parent elements to determine the open and closing states.

#### How did you test and verify your work?

The effects of the fix are visual, so (manually) compared how the chevron looks like and behaves during opening/closing, verified that the summary is visible on a nested options tile when it is collapsed.

### CODE REVIEW

**Comment by lakeside76** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by davidmenendez** [comment]
@lakeside76 thanks for taking a look at this. can you provide an image or preferably a video that demonstrates this fix since theres no nested `optionsTile` story we can verify against in the deploy preview?

**Comment by markusnosse** [comment]
@davidmenendez Sorry, missed your update asking for a video of the fix. Here you are:


https://github.com/carbon-design-system/ibm-products/assets/173772401/2c05880c-ffc1-4236-829c-3492cf2dbf9e


https://github.com/carbon-design-system/ibm-products/assets/173772401/b5108b16-31dd-47e4-8d66-ef1f3a61596a


https://github.com/carbon-design-system/ibm-products/assets/173772401/25638436-037b-4f82-9307-e5690db51750

**Review by matthewgallo — DISMISSED** [review]

**Review by davidmenendez — APPROVED** [review]

**Review by matthewgallo — APPROVED** [review]

**Comment by markusnosse** [comment]
Thank you very much @matthewgallo and @davidmenendez for accepting my contribution!

**Pull request merged**
