### PR TITLE
feat(SidePanel): adding tooltip

### LINKED ISSUE #4604: Sidepanel close button tooltip improvement
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

- Sidepanel usability can be improved by adding a tooltip for the close button, similar to the Carbon modal
- Not really an issue more of an enhancement to match Carbon design system

> Is this issue related to a specific component?

- Sidepanel

> What did you expect to happen? What happened instead? What would you like to
> see changed?

- Expected a tooltip when hovering over the close button with the icon description text

> What browser are you working in?

- Close

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

- `"@carbon/ibm-products": "2.26.0",`

## Additional information

Carbon modal
Screenshot 2024-03-25 at 3 23 54 PM

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by anamikaanu96**
Closes #4604

Added tooltip for the close button

### CODE REVIEW

**Comment by matthewgallo** [comment]
Hey @anamikaanu96, I have a feeling those tests are failing because the Carbon tooltip has an entrance delay which the test may not be accounting for. @elycheea made a good point about switching from `Button` to `IconButton` for the close icon as well with this change, similar to how Carbon does [here](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/ComposedModal/ModalHeader.tsx#L132).

**Comment by anamikaanu96** [comment]
Hey @matthewgallo, initially I tried switching from `Button` to `IconButton`, then also I faced the same issue. Now I am able to resolve it by using waitFor().
cc : @elycheea

**Review by sangeethababu9223 — APPROVED** [review]

**Comment by anamikaanu96** [comment]
Hey @matthewgallo as discussed , I used IconButton instead of Button.

**Review by matthewgallo — APPROVED** [review]
The close icon position for panels with left placement looks existing already actually! We can take a look at that separately.

**Review by sangeethababu9223 — APPROVED** [review]

**Pull request merged**
